# -*- coding: utf-8 -*-
"""Real Time Project sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1maigrPQX9oQAwQZ0AKQqL_jbQR2xhe6q
"""

import pandas as pd
import random
from datetime import datetime
import os

from datetime import datetime, timedelta

random_days = random.randint(0, 10)

data = {
    "OrderID": random.randint(1000, 9999),
    "Date": datetime.now() - timedelta(days=random_days),
    "Product": random.choice(products),
    "Region": random.choice(regions),
    "Sales": random.randint(50, 500),
    "Profit": random.randint(-50, 200)
}

import pandas as pd
import random
from datetime import datetime, timedelta
import os

file_path = "live_sales.csv"

products = ["Laptop", "Phone", "Tablet", "Headphones"]
regions = ["London", "Manchester", "Birmingham", "Leeds"]

random_days = random.randint(0, 10)

data = {
    "OrderID": random.randint(1000, 9999),
    "Date": datetime.now() - timedelta(days=random_days),
    "Product": random.choice(products),
    "Region": random.choice(regions),
    "Sales": random.randint(50, 500),
    "Profit": random.randint(-50, 200)
}

df = pd.DataFrame([data])

if os.path.exists(file_path):
    df.to_csv(file_path, mode='a', header=False, index=False)
else:
    df.to_csv(file_path, index=False)

print("Added:", data)

df = pd.read_csv("live_sales.csv")
df['Date'] = pd.to_datetime(df['Date'])

df['Date'].dt.date.unique()

df = pd.read_csv("live_sales.csv")

df['Date'] = pd.to_datetime(df['Date'])

df.head()

print("Total Sales:", df['Sales'].sum())
print("Total Profit:", df['Profit'].sum())

df.groupby('Product')['Sales'].sum().sort_values(ascending=False)

df.groupby('Region')['Profit'].sum().sort_values()

import matplotlib.pyplot as plt

df = pd.read_csv("live_sales.csv")
df['Date'] = pd.to_datetime(df['Date'])

df.set_index('Date', inplace=True)

df['Sales'].resample('D').sum().plot()
plt.title("Daily Sales Trend")
plt.xticks(rotation=45)
plt.show()

df.groupby('Product')['Sales'].sum().plot(kind='bar')
plt.title("Sales by Product")
plt.show()

df.groupby('Region')['Profit'].sum().plot(kind='bar')
plt.title("Profit by Region")
plt.show()

from google.colab import files
files.download("live_sales.csv")

df.sort_values('Date').head(10)

import os
os.remove("live_sales.csv")

import os

if os.path.exists("live_sales.csv"):
    os.remove("live_sales.csv")
    print("Old file deleted ✅")
else:
    print("No file found")

import pandas as pd
import matplotlib.pyplot as plt

# Load fresh data
df = pd.read_csv("live_sales.csv")

# Convert to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Set index
df.set_index('Date', inplace=True)

# Plot
df['Sales'].resample('D').sum().plot()
plt.title("Daily Sales Trend")
plt.xticks(rotation=45)
plt.show()